# Generated by Django 3.0.7 on 2020-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200619_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='result10th',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='result12th',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
