# Generated by Django 3.0.7 on 2020-06-21 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
