# Generated by Django 3.0.7 on 2020-06-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200628_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='EventPicture',
        ),
    ]
