# Generated by Django 3.0.7 on 2020-06-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpicture',
            name='featured',
            field=models.BooleanField(blank=True, default='True'),
            preserve_default=False,
        ),
    ]
